name: Update CF Adblock

on:
  schedule:
    - cron: '0 1,12 * * *'
  workflow_dispatch: 

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        TOKEN_MAIN: ${{ secrets.TOKEN_MAIN }}
      run: python cmmain.py
