name: rnxs-auto-parallel-nodes

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Matrix
        id: generate
        run: |
          # Menghitung jumlah node valid (mengabaikan komentar '#' dan baris kosong)
          NODE_COUNT=$(grep -v '^#' nid.txt | grep -v '^$' | wc -l)
          echo "Ditemukan $NODE_COUNT node valid."
          
          # Membuat array JSON [1, 2, 3, ..., N] untuk matrix
          JSON_ARRAY=$(seq 1 $NODE_COUNT | jq -R . | jq -s -c .)
          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT

  run-rnxs-node:
    needs: setup-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        node_index: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -q >/dev/null 2>&1
          sudo apt-get install -y -q expect curl jq wget >/dev/null 2>&1

      - name: Prepare Script
        run: |
          chmod +x rnxs.sh

      - name: Prepare single node
        run: |
          grep -v '^#' nid.txt | grep -v '^$' | sed -n "${{ matrix.node_index }}p" > my_node_${{ matrix.node_index }}.txt
          echo "Target Node untuk VM ini:"
          cat my_node_${{ matrix.node_index }}.txt

      - name: Run script
        env:
          WEBHOOK_1: ${{ secrets.WEBHOOK_1 }}
          WEBHOOK_2: ${{ secrets.WEBHOOK_2 }}
          WEBHOOK_3: ${{ secrets.WEBHOOK_3 }}
          REFRESH_SUCCESS_TARGET: 2
          REFRESH_ACCUMULATE: 1
          CONCURRENCY: 1
          LOOP_MODE: "once"
          LOG_MODE: "logfull"
          SEND_DISCORD: 1
          MODE: "refresh"
          NID: my_node_${{ matrix.node_index }}.txt
        run: |
          [ -s "my_node_${{ matrix.node_index }}.txt" ] && ./rnxs.sh ${{ matrix.node_index }} || true

      - name: Cleanup
        if: always()
        run: |
          rm -f my_node_*.txt
          rm -f /tmp/nexus_* /tmp/*.log
          rm -f rnxs.sh
          rm -rf /home/runner/.nexus/bin/nexus-network
          true
