name: Upshift

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  run-upshift-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Decrypt Files
      env:
        SCRIPT_PASSPHRASE: ${{ secrets.SCRIPT_PASSPHRASE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$SCRIPT_PASSPHRASE" --output upshift.py upshift.py.gpg
        gpg --quiet --batch --yes --decrypt --passphrase="$SCRIPT_PASSPHRASE" --output upshift.txt upshift.txt.gpg

    - name: Run Script
      env:
        WEBHOOK_UPSHIFT: ${{ secrets.WEBHOOK_UPSHIFT }}
      run: |
        python upshift.py > /dev/null 2>&1

    - name: Cleanup Secrets and Logs
      if: always()
      run: |
        rm -f upshift.py
        rm -f upshift.txt
        echo "Cleanup completed successfully."
